script = """
4 % 2
"""

[output]
result = "0"
type = "integer"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 27, 0, 0, 0, 4, 27, 0, 0, 0, 2, 4, 38]"
bytecode_length = 18
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: 4)
11 \tpush_integer (value: 2)
16 \tint_mod
17 \tret
"""

[output.vm]
bytes_read = 19
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
