script = """
4.0 %. 2.0
"""

[output]
result = "0.00"
type = "float"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 28, 64, 128, 0, 0, 28, 64, 0, 0, 0, 11, 40]"
bytecode_length = 18
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: 4)
11 \tpush_float (value: 2)
16 \tfloat_mod
17 \tret
"""

[output.vm]
bytes_read = 19
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
