script = """
5.4 %. 2.1
"""

[output]
result = "1.20"
type = "float"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 28, 64, 172, 204, 205, 28, 64, 6, 102, 102, 11, 40]"
bytecode_length = 19
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_float (value: 5.4)
12 \tpush_float (value: 2.1)
17 \tfloat_mod
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
