script = """
1 + 2 + 3 + 4 + 5
"""

[output]
result = "15"
type = "integer"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 1, 29, 0, 0, 0, 2, 0, 29, 0, 0, 0, 3, 0, 29, 0, 0, 0, 4, 0, 29, 0, 0, 0, 5, 0, 40]"
bytecode_length = 37
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 1)
12 \tpush_integer (value: 2)
17 \tint_add
18 \tpush_integer (value: 3)
23 \tint_add
24 \tpush_integer (value: 4)
29 \tint_add
30 \tpush_integer (value: 5)
35 \tint_add
36 \tret
"""

[output.vm]
bytes_read = 38
instructions_executed = 11
jumps_performed = 0
max_stack_height = 2
stack_allocations = 10
