script = """
1.1 +. 2.2 +. 3.3 +. 4.4 +. 5.5
"""

[output]
result = "16.50"
type = "float"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 28, 63, 140, 204, 205, 28, 64, 12, 204, 205, 7, 28, 64, 83, 51, 51, 7, 28, 64, 140, 204, 205, 7, 28, 64, 176, 0, 0, 7, 40]"
bytecode_length = 36
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: 1.1)
11 \tpush_float (value: 2.2)
16 \tfloat_add
17 \tpush_float (value: 3.3)
22 \tfloat_add
23 \tpush_float (value: 4.4)
28 \tfloat_add
29 \tpush_float (value: 5.5)
34 \tfloat_add
35 \tret
"""

[output.vm]
bytes_read = 37
instructions_executed = 11
jumps_performed = 0
max_stack_height = 2
stack_allocations = 10
