script = """
1.1 +. 2.2 +. 3.3 +. 4.4 +. 5.5
"""

[output]
result = "16.50"
type = "float"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 28, 63, 140, 204, 205, 28, 64, 12, 204, 205, 7, 28, 64, 83, 51, 51, 7, 28, 64, 140, 204, 205, 7, 28, 64, 176, 0, 0, 7, 40]"
bytecode_length = 37
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_float (value: 1.1)
12 \tpush_float (value: 2.2)
17 \tfloat_add
18 \tpush_float (value: 3.3)
23 \tfloat_add
24 \tpush_float (value: 4.4)
29 \tfloat_add
30 \tpush_float (value: 5.5)
35 \tfloat_add
36 \tret
"""

[output.vm]
bytes_read = 38
instructions_executed = 11
jumps_performed = 0
max_stack_height = 2
stack_allocations = 10
