script = """
2.5 is
    other if other >=. 2.0 and other <. 3.0
        "captured {other}"
"""

[output]
result = "captured 2.5"
type = "string"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 26, 64, 32, 0, 0, 21, 0, 20, 0, 26, 64, 0, 0, 0, 12, 19, 20, 0, 26, 64, 64, 0, 0, 12, 15, 44, 0, 14, 28, 9, 99, 97, 112, 116, 117, 114, 101, 100, 32, 20, 0, 14, 38]"
bytecode_length = 49
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: 2.5)
11 \tset_value (index: 0)
13 \tget_value (index: 0)
15 \tpush_float (value: 2)
20 \tfloat_lt
21 \tnot
22 \tget_value (index: 0)
24 \tpush_float (value: 3)
29 \tfloat_lt
30 \tand
31 \tjump if false (offset: 14, to byte 48)
34 \tpush_string (value: 'captured ')
45 \tget_value (index: 0)
47 \tstr_concat
48 \tret
"""

[output.vm]
bytes_read = 50
instructions_executed = 16
jumps_performed = 0
max_stack_height = 4
stack_allocations = 13
