script = """
2.3 is
    other if other <=. 2.0
        "nope"
    other if other >=. 2.0
        "value captured is {other}"
"""

[output]
result = "value captured is 2.3"
type = "string"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 28, 64, 19, 51, 51, 21, 0, 20, 0, 28, 64, 0, 0, 0, 13, 46, 0, 9, 30, 4, 110, 111, 112, 101, 44, 0, 35, 20, 0, 28, 64, 0, 0, 0, 12, 19, 46, 0, 23, 30, 18, 118, 97, 108, 117, 101, 32, 99, 97, 112, 116, 117, 114, 101, 100, 32, 105, 115, 32, 20, 0, 14, 40]"
bytecode_length = 69
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: 2.3)
11 \tset_value (index: 0)
13 \tget_value (index: 0)
15 \tpush_float (value: 2)
20 \tfloat_lte
21 \tjump if false (offset: 9, to byte 33)
24 \tpush_string (value: 'nope')
30 \tjump (offset: 35, to byte 68)
33 \tget_value (index: 0)
35 \tpush_float (value: 2)
40 \tfloat_lt
41 \tnot
42 \tjump if false (offset: 23, to byte 68)
45 \tpush_string (value: 'value captured is ')
65 \tget_value (index: 0)
67 \tstr_concat
68 \tret
"""

[output.vm]
bytes_read = 61
instructions_executed = 16
jumps_performed = 1
max_stack_height = 3
stack_allocations = 12
