script = """
2.5 is
    other if other >=. 2.0 and other <. 3.0
        "captured {other}"
"""

[output]
result = "captured 2.5"
type = "string"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 28, 64, 32, 0, 0, 21, 0, 20, 0, 28, 64, 0, 0, 0, 12, 19, 20, 0, 28, 64, 64, 0, 0, 12, 15, 46, 0, 14, 30, 9, 99, 97, 112, 116, 117, 114, 101, 100, 32, 20, 0, 14, 40]"
bytecode_length = 50
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_float (value: 2.5)
12 \tset_value (index: 0)
14 \tget_value (index: 0)
16 \tpush_float (value: 2)
21 \tfloat_lt
22 \tnot
23 \tget_value (index: 0)
25 \tpush_float (value: 3)
30 \tfloat_lt
31 \tand
32 \tjump if false (offset: 14, to byte 49)
35 \tpush_string (value: 'captured ')
46 \tget_value (index: 0)
48 \tstr_concat
49 \tret
"""

[output.vm]
bytes_read = 51
instructions_executed = 16
jumps_performed = 0
max_stack_height = 4
stack_allocations = 13
