script = """
2 is
    1
        "no"
    other if other >= 2
        "value captured is {other}"
"""

[output]
result = "value captured is 2"
type = "string"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 27, 0, 0, 0, 2, 21, 0, 20, 0, 27, 0, 0, 0, 1, 17, 44, 0, 7, 28, 2, 110, 111, 42, 0, 35, 20, 0, 27, 0, 0, 0, 2, 5, 19, 44, 0, 23, 28, 18, 118, 97, 108, 117, 101, 32, 99, 97, 112, 116, 117, 114, 101, 100, 32, 105, 115, 32, 20, 0, 14, 38]"
bytecode_length = 67
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: 2)
11 \tset_value (index: 0)
13 \tget_value (index: 0)
15 \tpush_integer (value: 1)
20 \teq
21 \tjump if false (offset: 7, to byte 31)
24 \tpush_string (value: 'no')
28 \tjump (offset: 35, to byte 66)
31 \tget_value (index: 0)
33 \tpush_integer (value: 2)
38 \tint_lt
39 \tnot
40 \tjump if false (offset: 23, to byte 66)
43 \tpush_string (value: 'value captured is ')
63 \tget_value (index: 0)
65 \tstr_concat
66 \tret
"""

[output.vm]
bytes_read = 61
instructions_executed = 16
jumps_performed = 1
max_stack_height = 3
stack_allocations = 12
