script = """
5 is
    5 if false
        "no"
    5 if true
        "yes"
    5
        "also no"
"""

[output]
result = "yes"
type = "string"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 5, 21, 0, 20, 0, 29, 0, 0, 0, 5, 17, 46, 0, 11, 27, 46, 0, 7, 30, 2, 110, 111, 44, 0, 43, 20, 0, 29, 0, 0, 0, 5, 17, 46, 0, 12, 26, 46, 0, 8, 30, 3, 121, 101, 115, 44, 0, 20, 20, 0, 29, 0, 0, 0, 5, 17, 46, 0, 9, 30, 7, 97, 108, 115, 111, 32, 110, 111, 40]"
bytecode_length = 80
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 5)
12 \tset_value (index: 0)
14 \tget_value (index: 0)
16 \tpush_integer (value: 5)
21 \teq
22 \tjump if false (offset: 11, to byte 36)
25 \tpush_false
26 \tjump if false (offset: 7, to byte 36)
29 \tpush_string (value: 'no')
33 \tjump (offset: 43, to byte 79)
36 \tget_value (index: 0)
38 \tpush_integer (value: 5)
43 \teq
44 \tjump if false (offset: 12, to byte 59)
47 \tpush_true
48 \tjump if false (offset: 8, to byte 59)
51 \tpush_string (value: 'yes')
56 \tjump (offset: 20, to byte 79)
59 \tget_value (index: 0)
61 \tpush_integer (value: 5)
66 \teq
67 \tjump if false (offset: 9, to byte 79)
70 \tpush_string (value: 'also no')
79 \tret
"""

[output.vm]
bytes_read = 54
instructions_executed = 18
jumps_performed = 2
max_stack_height = 3
stack_allocations = 11
