script = """
0 >= 0
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 27, 0, 0, 0, 0, 27, 0, 0, 0, 0, 5, 19, 38]"
bytecode_length = 19
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: 0)
11 \tpush_integer (value: 0)
16 \tint_lt
17 \tnot
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 5
