script = """
-3.45 <. -2.34
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 28, 192, 92, 204, 205, 28, 192, 21, 194, 143, 12, 40]"
bytecode_length = 19
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_float (value: -3.45)
12 \tpush_float (value: -2.34)
17 \tfloat_lt
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
