script = """
-0.9 >. -1.0
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 28, 191, 102, 102, 102, 28, 191, 128, 0, 0, 13, 19, 40]"
bytecode_length = 20
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_float (value: -0.9)
12 \tpush_float (value: -1)
17 \tfloat_lte
18 \tnot
19 \tret
"""

[output.vm]
bytes_read = 21
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 5
