script = """
-0.9 >. -1.0
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[35, 4, 109, 97, 105, 110, 26, 191, 102, 102, 102, 26, 191, 128, 0, 0, 13, 19, 37]"
bytecode_length = 19
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: -0.9)
11 \tpush_float (value: -1)
16 \tfloat_lte
17 \tnot
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 5
