script = """
-5.67 >=. -5.67
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[35, 4, 109, 97, 105, 110, 26, 192, 181, 112, 164, 26, 192, 181, 112, 164, 12, 19, 37]"
bytecode_length = 19
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: -5.67)
11 \tpush_float (value: -5.67)
16 \tfloat_lt
17 \tnot
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 5
