script = """
-0.0 >=. -0.0
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 28, 128, 0, 0, 0, 28, 128, 0, 0, 0, 12, 19, 40]"
bytecode_length = 19
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: -0)
11 \tpush_float (value: -0)
16 \tfloat_lt
17 \tnot
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 5
