script = """
-5 >= -5
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 29, 255, 255, 255, 251, 29, 255, 255, 255, 251, 5, 19, 40]"
bytecode_length = 19
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: -5)
11 \tpush_integer (value: -5)
16 \tint_lt
17 \tnot
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 5
