script = """
3 == 1 + 2
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 3, 29, 0, 0, 0, 1, 29, 0, 0, 0, 2, 0, 17, 40]"
bytecode_length = 25
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 3)
12 \tpush_integer (value: 1)
17 \tpush_integer (value: 2)
22 \tint_add
23 \teq
24 \tret
"""

[output.vm]
bytes_read = 26
instructions_executed = 7
jumps_performed = 0
max_stack_height = 3
stack_allocations = 6
