script = """
1 == 1
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 1, 29, 0, 0, 0, 1, 17, 40]"
bytecode_length = 18
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: 1)
11 \tpush_integer (value: 1)
16 \teq
17 \tret
"""

[output.vm]
bytes_read = 19
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
