script = """
-0.3 == -0.3
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 28, 190, 153, 153, 154, 28, 190, 153, 153, 154, 17, 40]"
bytecode_length = 18
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: -0.3)
11 \tpush_float (value: -0.3)
16 \teq
17 \tret
"""

[output.vm]
bytes_read = 19
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
