script = """
true == false
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[35, 4, 109, 97, 105, 110, 24, 25, 17, 37]"
bytecode_length = 10
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_true
7 \tpush_false
8 \teq
9 \tret
"""

[output.vm]
bytes_read = 11
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
