script = """
-12.3 == 12.3
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[35, 4, 109, 97, 105, 110, 26, 193, 68, 204, 205, 26, 65, 68, 204, 205, 17, 37]"
bytecode_length = 18
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: -12.3)
11 \tpush_float (value: 12.3)
16 \teq
17 \tret
"""

[output.vm]
bytes_read = 19
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
