script = """
-3 == -5
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 29, 255, 255, 255, 253, 29, 255, 255, 255, 251, 17, 40]"
bytecode_length = 18
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: -3)
11 \tpush_integer (value: -5)
16 \teq
17 \tret
"""

[output.vm]
bytes_read = 19
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
