script = """
1 + 1 == 3
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 1, 29, 0, 0, 0, 1, 0, 29, 0, 0, 0, 3, 17, 40]"
bytecode_length = 25
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 1)
12 \tpush_integer (value: 1)
17 \tint_add
18 \tpush_integer (value: 3)
23 \teq
24 \tret
"""

[output.vm]
bytes_read = 26
instructions_executed = 7
jumps_performed = 0
max_stack_height = 2
stack_allocations = 6
