script = """
"Hello!" == "Hello!"
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 30, 6, 72, 101, 108, 108, 111, 33, 30, 6, 72, 101, 108, 108, 111, 33, 17, 40]"
bytecode_length = 25
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_string (value: 'Hello!')
15 \tpush_string (value: 'Hello!')
23 \teq
24 \tret
"""

[output.vm]
bytes_read = 26
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
