script = """
"Hello" == "World"
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 30, 5, 72, 101, 108, 108, 111, 30, 5, 87, 111, 114, 108, 100, 17, 40]"
bytecode_length = 23
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_string (value: 'Hello')
14 \tpush_string (value: 'World')
21 \teq
22 \tret
"""

[output.vm]
bytes_read = 24
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
