script = """
1 + 2 == 3
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 27, 0, 0, 0, 1, 27, 0, 0, 0, 2, 0, 27, 0, 0, 0, 3, 17, 38]"
bytecode_length = 24
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: 1)
11 \tpush_integer (value: 2)
16 \tint_add
17 \tpush_integer (value: 3)
22 \teq
23 \tret
"""

[output.vm]
bytes_read = 25
instructions_executed = 7
jumps_performed = 0
max_stack_height = 2
stack_allocations = 6
