script = """
-12.3 == 12.3
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 28, 193, 68, 204, 205, 28, 65, 68, 204, 205, 17, 40]"
bytecode_length = 19
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_float (value: -12.3)
12 \tpush_float (value: 12.3)
17 \teq
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
