script = """
"" == ""
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 30, 0, 30, 0, 17, 40]"
bytecode_length = 12
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_string (value: '')
8 \tpush_string (value: '')
10 \teq
11 \tret
"""

[output.vm]
bytes_read = 13
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
