script = """
-12.3 == -12.0
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 26, 193, 68, 204, 205, 26, 193, 64, 0, 0, 17, 38]"
bytecode_length = 18
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: -12.3)
11 \tpush_float (value: -12)
16 \teq
17 \tret
"""

[output.vm]
bytes_read = 19
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
