script = """
"" == ""
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 30, 0, 30, 0, 17, 40]"
bytecode_length = 13
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_string (value: '')
9 \tpush_string (value: '')
11 \teq
12 \tret
"""

[output.vm]
bytes_read = 14
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
