script = """
true != false
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 26, 27, 17, 19, 40]"
bytecode_length = 12
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_true
8 \tpush_false
9 \teq
10 \tnot
11 \tret
"""

[output.vm]
bytes_read = 13
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 5
