script = """
2 != 4
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 2, 29, 0, 0, 0, 4, 17, 19, 40]"
bytecode_length = 20
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 2)
12 \tpush_integer (value: 4)
17 \teq
18 \tnot
19 \tret
"""

[output.vm]
bytes_read = 21
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 5
