script = """
2 != 4
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[35, 4, 109, 97, 105, 110, 27, 0, 0, 0, 2, 27, 0, 0, 0, 4, 17, 19, 37]"
bytecode_length = 19
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: 2)
11 \tpush_integer (value: 4)
16 \teq
17 \tnot
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 5
