script = """
2 != 1 + 2
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 2, 29, 0, 0, 0, 1, 29, 0, 0, 0, 2, 0, 17, 19, 40]"
bytecode_length = 25
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: 2)
11 \tpush_integer (value: 1)
16 \tpush_integer (value: 2)
21 \tint_add
22 \teq
23 \tnot
24 \tret
"""

[output.vm]
bytes_read = 26
instructions_executed = 8
jumps_performed = 0
max_stack_height = 3
stack_allocations = 7
