script = """
"Hello" != "World"
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 28, 5, 72, 101, 108, 108, 111, 28, 5, 87, 111, 114, 108, 100, 17, 19, 38]"
bytecode_length = 23
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_string (value: 'Hello')
13 \tpush_string (value: 'World')
20 \teq
21 \tnot
22 \tret
"""

[output.vm]
bytes_read = 24
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 5
