script = '''
blah = \v
	:hello v
4 | blah
'''

[output]
result = ":hello(4)"
type = "tag"

[output.compiler]
bytecode = "[0, 37, 4, 98, 108, 97, 104, 1, 0, 36, 38, 4, 109, 97, 105, 110, 39, 0, 1, 21, 0, 29, 0, 0, 0, 4, 41, 1, 0, 0, 4, 98, 108, 97, 104, 40, 38, 4, 98, 108, 97, 104, 20, 0, 34, 6, 58, 104, 101, 108, 108, 111, 40]"
bytecode_length = 53
disassembled = """
0 \tComponent Count: 0
1 \tfunction signature (name: blah) (local count: 1) (function position: 36)

10 \t=== function chunk: main ===
16 \tfunction (function index: 0) (params: 1)
19 \tset_value (index: 0)
21 \tpush_integer (value: 4)
26 \tcall blah (is_global: 0) (arg count: 1, function index: 0)
35 \tret

36 \t=== function chunk: blah ===
42 \tget_value (index: 0)
44 \tpush_tag (value: ':hello')
52 \tret
"""

[output.vm]
bytes_read = 54
instructions_executed = 10
jumps_performed = 0
max_stack_height = 3
stack_allocations = 6
