script = '''
blah = \v
	:hello v
4 | blah
'''

[output]
result = ":hello(4)"
type = "tag"

[output.compiler]
bytecode = "[35, 4, 98, 108, 97, 104, 1, 0, 35, 36, 4, 109, 97, 105, 110, 37, 0, 1, 21, 0, 27, 0, 0, 0, 4, 39, 1, 0, 0, 4, 98, 108, 97, 104, 38, 36, 4, 98, 108, 97, 104, 20, 0, 32, 6, 58, 104, 101, 108, 108, 111, 38]"
bytecode_length = 52
disassembled = """
0 \tfunction signature (name: blah) (local count: 1) (function position: 35)

9 \t=== function chunk: main ===
15 \tfunction (function index: 0) (params: 1)
18 \tset_value (index: 0)
20 \tpush_integer (value: 4)
25 \tcall blah (is_global: 0) (arg count: 1, function index: 0)
34 \tret

35 \t=== function chunk: blah ===
41 \tget_value (index: 0)
43 \tpush_tag (value: ':hello')
51 \tret
"""

[output.vm]
bytes_read = 53
instructions_executed = 10
jumps_performed = 0
max_stack_height = 3
stack_allocations = 6
