script = """
value = 45
:color value
"""

[output]
result = ":color(45)"
type = "tag"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 45, 21, 0, 20, 0, 34, 6, 58, 99, 111, 108, 111, 114, 40]"
bytecode_length = 25
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 45)
12 \tset_value (index: 0)
14 \tget_value (index: 0)
16 \tpush_tag (value: ':color')
24 \tret
"""

[output.vm]
bytes_read = 26
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
