script = """
value = 45
:color value
"""

[output]
result = ":color(45)"
type = "tag"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 45, 21, 0, 20, 0, 34, 6, 58, 99, 111, 108, 111, 114, 40]"
bytecode_length = 24
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: 45)
11 \tset_value (index: 0)
13 \tget_value (index: 0)
15 \tpush_tag (value: ':color')
23 \tret
"""

[output.vm]
bytes_read = 25
instructions_executed = 6
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
