script = """
x = 2
3 + x is
\tcaptured
\t\tw = 0
\t\tcaptured + x + w
"""

[output]
result = "7"
type = "integer"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 2, 21, 0, 29, 0, 0, 0, 3, 20, 0, 0, 21, 1, 29, 0, 0, 0, 0, 21, 2, 20, 1, 20, 0, 0, 20, 2, 0, 40]"
bytecode_length = 39
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: 2)
11 \tset_value (index: 0)
13 \tpush_integer (value: 3)
18 \tget_value (index: 0)
20 \tint_add
21 \tset_value (index: 1)
23 \tpush_integer (value: 0)
28 \tset_value (index: 2)
30 \tget_value (index: 1)
32 \tget_value (index: 0)
34 \tint_add
35 \tget_value (index: 2)
37 \tint_add
38 \tret
"""

[output.vm]
bytes_read = 40
instructions_executed = 15
jumps_performed = 0
max_stack_height = 5
stack_allocations = 11
