script = """
:xyz is
    :ok contents
        "result is ok: {contents}"
    :error desc
        "result is error: {desc}"
    x
        "nothing matches: {x}"
"""

[output]
result = "nothing matches: :xyz"
type = "string"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 31, 4, 58, 120, 121, 122, 21, 0, 33, 28, 3, 58, 111, 107, 17, 44, 0, 25, 34, 21, 0, 28, 14, 114, 101, 115, 117, 108, 116, 32, 105, 115, 32, 111, 107, 58, 32, 20, 0, 14, 42, 0, 71, 33, 28, 6, 58, 101, 114, 114, 111, 114, 17, 44, 0, 28, 34, 21, 0, 28, 17, 114, 101, 115, 117, 108, 116, 32, 105, 115, 32, 101, 114, 114, 111, 114, 58, 32, 20, 0, 14, 42, 0, 30, 31, 4, 58, 120, 121, 122, 21, 0, 28, 17, 110, 111, 116, 104, 105, 110, 103, 32, 109, 97, 116, 99, 104, 101, 115, 58, 32, 20, 0, 14, 38]"
bytecode_length = 121
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_simple_tag (value: ':xyz')
12 \tset_value (index: 0)
14 \tget_tag_name
15 \tpush_string (value: ':ok')
20 \teq
21 \tjump if false (offset: 25, to byte 49)
24 \tget_tag_payload
25 \tset_value (index: 0)
27 \tpush_string (value: 'result is ok: ')
43 \tget_value (index: 0)
45 \tstr_concat
46 \tjump (offset: 71, to byte 120)
49 \tget_tag_name
50 \tpush_string (value: ':error')
58 \teq
59 \tjump if false (offset: 28, to byte 90)
62 \tget_tag_payload
63 \tset_value (index: 0)
65 \tpush_string (value: 'result is error: ')
84 \tget_value (index: 0)
86 \tstr_concat
87 \tjump (offset: 30, to byte 120)
90 \tpush_simple_tag (value: ':xyz')
96 \tset_value (index: 0)
98 \tpush_string (value: 'nothing matches: ')
117 \tget_value (index: 0)
119 \tstr_concat
120 \tret
"""

[output.vm]
bytes_read = 69
instructions_executed = 17
jumps_performed = 2
max_stack_height = 3
stack_allocations = 12
