script = '''
stoplight_color = \v
	v is
		x if x >. 0.0
			:red
		x if x == 0.0
			:yellow 4
		_
			:green
first = 5.0 | stoplight_color
second = 0.0 | stoplight_color
third = -3.2 | stoplight_color

"Lights: {first} => {second} => {third}"
'''

[output]
result = "Lights: :red => :yellow(4) => :green"
type = "string"

[output.compiler]
bytecode = "[35, 15, 115, 116, 111, 112, 108, 105, 103, 104, 116, 95, 99, 111, 108, 111, 114, 1, 0, 146, 36, 4, 109, 97, 105, 110, 37, 0, 1, 21, 0, 26, 64, 160, 0, 0, 39, 1, 0, 0, 15, 115, 116, 111, 112, 108, 105, 103, 104, 116, 95, 99, 111, 108, 111, 114, 21, 1, 26, 0, 0, 0, 0, 39, 1, 0, 0, 15, 115, 116, 111, 112, 108, 105, 103, 104, 116, 95, 99, 111, 108, 111, 114, 21, 2, 26, 192, 76, 204, 205, 39, 1, 0, 0, 15, 115, 116, 111, 112, 108, 105, 103, 104, 116, 95, 99, 111, 108, 111, 114, 21, 3, 28, 8, 76, 105, 103, 104, 116, 115, 58, 32, 20, 1, 14, 28, 4, 32, 61, 62, 32, 14, 20, 2, 14, 28, 4, 32, 61, 62, 32, 14, 20, 3, 14, 38, 36, 15, 115, 116, 111, 112, 108, 105, 103, 104, 116, 95, 99, 111, 108, 111, 114, 20, 0, 21, 1, 20, 1, 26, 0, 0, 0, 0, 13, 19, 44, 0, 9, 31, 4, 58, 114, 101, 100, 42, 0, 40, 20, 0, 21, 2, 20, 2, 26, 0, 0, 0, 0, 17, 44, 0, 17, 27, 0, 0, 0, 4, 32, 7, 58, 121, 101, 108, 108, 111, 119, 42, 0, 8, 31, 6, 58, 103, 114, 101, 101, 110, 38]"
bytecode_length = 229
disassembled = """
0 \tfunction signature (name: stoplight_color) (local count: 1) (function position: 146)

20 \t=== function chunk: main ===
26 \tfunction (function index: 0) (params: 1)
29 \tset_value (index: 0)
31 \tpush_float (value: 5)
36 \tcall stoplight_color (is_global: 0) (arg count: 1, function index: 0)
56 \tset_value (index: 1)
58 \tpush_float (value: 0)
63 \tcall stoplight_color (is_global: 0) (arg count: 1, function index: 0)
83 \tset_value (index: 2)
85 \tpush_float (value: -3.2)
90 \tcall stoplight_color (is_global: 0) (arg count: 1, function index: 0)
110 \tset_value (index: 3)
112 \tpush_string (value: 'Lights: ')
122 \tget_value (index: 1)
124 \tstr_concat
125 \tpush_string (value: ' => ')
131 \tstr_concat
132 \tget_value (index: 2)
134 \tstr_concat
135 \tpush_string (value: ' => ')
141 \tstr_concat
142 \tget_value (index: 3)
144 \tstr_concat
145 \tret

146 \t=== function chunk: stoplight_color ===
163 \tget_value (index: 0)
165 \tset_value (index: 1)
167 \tget_value (index: 1)
169 \tpush_float (value: 0)
174 \tfloat_lte
175 \tnot
176 \tjump if false (offset: 9, to byte 188)
179 \tpush_simple_tag (value: ':red')
185 \tjump (offset: 40, to byte 228)
188 \tget_value (index: 0)
190 \tset_value (index: 2)
192 \tget_value (index: 2)
194 \tpush_float (value: 0)
199 \teq
200 \tjump if false (offset: 17, to byte 220)
203 \tpush_integer (value: 4)
208 \tpush_tag (value: ':yellow')
217 \tjump (offset: 8, to byte 228)
220 \tpush_simple_tag (value: ':green')
228 \tret
"""

[output.vm]
bytes_read = 313
instructions_executed = 69
jumps_performed = 5
max_stack_height = 8
stack_allocations = 46
