script = """
54.32 /. 0.0
"""

[output]
result = "0.00"
type = "float"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 28, 66, 89, 71, 174, 28, 0, 0, 0, 0, 9, 40]"
bytecode_length = 19
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_float (value: 54.32)
12 \tpush_float (value: 0)
17 \tfloat_div
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
