script = """
10 / 0
"""

[output]
result = "0"
type = "integer"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 10, 29, 0, 0, 0, 0, 2, 40]"
bytecode_length = 19
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 10)
12 \tpush_integer (value: 0)
17 \tint_div
18 \tret
"""

[output.vm]
bytes_read = 20
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
