script = """
54.32 /. 0.0
"""

[output]
result = "0.00"
type = "float"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 26, 66, 89, 71, 174, 26, 0, 0, 0, 0, 9, 38]"
bytecode_length = 18
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: 54.32)
11 \tpush_float (value: 0)
16 \tfloat_div
17 \tret
"""

[output.vm]
bytes_read = 19
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
