script = """
x = 42.3
y = 0.0
x /. y
"""

[output]
result = "0"
type = "float"

[output.compiler]
bytecode = "[35, 4, 109, 97, 105, 110, 26, 66, 41, 51, 51, 21, 0, 26, 0, 0, 0, 0, 21, 1, 20, 0, 20, 1, 9, 37]"
bytecode_length = 26
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: 42.3)
11 \tset_value (index: 0)
13 \tpush_float (value: 0)
18 \tset_value (index: 1)
20 \tget_value (index: 0)
22 \tget_value (index: 1)
24 \tfloat_div
25 \tret
"""

[output.vm]
bytes_read = 27
instructions_executed = 9
jumps_performed = 0
max_stack_height = 4
stack_allocations = 6
