script = """
x = 42
y = 0
x / y
"""

[output]
result = "0"
type = "integer"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 42, 21, 0, 29, 0, 0, 0, 0, 21, 1, 20, 0, 20, 1, 2, 40]"
bytecode_length = 27
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 42)
12 \tset_value (index: 0)
14 \tpush_integer (value: 0)
19 \tset_value (index: 1)
21 \tget_value (index: 0)
23 \tget_value (index: 1)
25 \tint_div
26 \tret
"""

[output.vm]
bytes_read = 28
instructions_executed = 9
jumps_performed = 0
max_stack_height = 4
stack_allocations = 6
