script = '''
match = \tag
	tag is
		x
			"captured value {x}"
(:yellow 4) | match
'''

[output]
result = "captured value :yellow(4)"
type = "string"

[output.compiler]
bytecode = "[35, 5, 109, 97, 116, 99, 104, 1, 0, 45, 36, 4, 109, 97, 105, 110, 37, 0, 1, 21, 0, 27, 0, 0, 0, 4, 32, 6, 121, 101, 108, 108, 111, 119, 39, 1, 0, 0, 5, 109, 97, 116, 99, 104, 38, 36, 5, 109, 97, 116, 99, 104, 20, 0, 21, 1, 28, 15, 99, 97, 112, 116, 117, 114, 101, 100, 32, 118, 97, 108, 117, 101, 32, 20, 1, 14, 38]"
bytecode_length = 77
disassembled = """
0 \tfunction signature (name: match) (local count: 1) (function position: 45)

10 \t=== function chunk: main ===
16 \tfunction (function index: 0) (params: 1)
19 \tset_value (index: 0)
21 \tpush_integer (value: 4)
26 \tpush_tag (value: ':yellow')
34 \tcall match (is_global: 0) (arg count: 1, function index: 0)
44 \tret

45 \t=== function chunk: match ===
52 \tget_value (index: 0)
54 \tset_value (index: 1)
56 \tpush_string (value: 'captured value ')
73 \tget_value (index: 1)
75 \tstr_concat
76 \tret
"""

[output.vm]
bytes_read = 78
instructions_executed = 14
jumps_performed = 0
max_stack_height = 5
stack_allocations = 9
