script = """
x = 3.3
x is
    _ if x >. 0.0
        3
"""

[output]
result = "3"
type = "integer"

[output.compiler]
bytecode = "[35, 4, 109, 97, 105, 110, 26, 64, 83, 51, 51, 21, 0, 20, 0, 26, 0, 0, 0, 0, 13, 19, 43, 0, 5, 27, 0, 0, 0, 3, 37]"
bytecode_length = 31
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: 3.3)
11 \tset_value (index: 0)
13 \tget_value (index: 0)
15 \tpush_float (value: 0)
20 \tfloat_lte
21 \tnot
22 \tjump if false (offset: 5, to byte 30)
25 \tpush_integer (value: 3)
30 \tret
"""

[output.vm]
bytes_read = 32
instructions_executed = 10
jumps_performed = 0
max_stack_height = 3
stack_allocations = 7
