script = '''
stoplight_color = \v
	v is
		_ if v >. 0.0
			:red
		_ if v == 0.0
			:yellow 4
		_
			:green
0.0 | stoplight_color
'''

[output]
result = ":yellow(4)"
type = "tag"

[output.compiler]
bytecode = "[35, 15, 115, 116, 111, 112, 108, 105, 103, 104, 116, 95, 99, 111, 108, 111, 114, 1, 0, 57, 36, 4, 109, 97, 105, 110, 37, 0, 1, 21, 0, 26, 0, 0, 0, 0, 39, 1, 0, 0, 15, 115, 116, 111, 112, 108, 105, 103, 104, 116, 95, 99, 111, 108, 111, 114, 38, 36, 15, 115, 116, 111, 112, 108, 105, 103, 104, 116, 95, 99, 111, 108, 111, 114, 20, 0, 26, 0, 0, 0, 0, 13, 19, 44, 0, 9, 31, 4, 58, 114, 101, 100, 42, 0, 36, 20, 0, 26, 0, 0, 0, 0, 17, 44, 0, 17, 27, 0, 0, 0, 4, 32, 7, 58, 121, 101, 108, 108, 111, 119, 42, 0, 8, 31, 6, 58, 103, 114, 101, 101, 110, 38]"
bytecode_length = 132
disassembled = """
0 \tfunction signature (name: stoplight_color) (local count: 1) (function position: 57)

20 \t=== function chunk: main ===
26 \tfunction (function index: 0) (params: 1)
29 \tset_value (index: 0)
31 \tpush_float (value: 0)
36 \tcall stoplight_color (is_global: 0) (arg count: 1, function index: 0)
56 \tret

57 \t=== function chunk: stoplight_color ===
74 \tget_value (index: 0)
76 \tpush_float (value: 0)
81 \tfloat_lte
82 \tnot
83 \tjump if false (offset: 9, to byte 95)
86 \tpush_simple_tag (value: ':red')
92 \tjump (offset: 36, to byte 131)
95 \tget_value (index: 0)
97 \tpush_float (value: 0)
102 \teq
103 \tjump if false (offset: 17, to byte 123)
106 \tpush_integer (value: 4)
111 \tpush_tag (value: ':yellow')
120 \tjump (offset: 8, to byte 131)
123 \tpush_simple_tag (value: ':green')
131 \tret
"""

[output.vm]
bytes_read = 116
instructions_executed = 20
jumps_performed = 2
max_stack_height = 4
stack_allocations = 13
