script = """
3 is
    _
        "ok"
    3
        "not okay"
"""

[output]
error = """
        "not okay"
                 \u001B[33m^\u001B[0m
Line 5.18: Parse error: Unreachable due to default arm above."""
