script = """
3 is
    _
        "ok"
    _
        "not okay"
"""

[output]
error = """
        "not okay"
                 \u001B[33m^\u001B[0m
Line 5.18: Parse error: An `is` block cannot have multiple default arms."""
