script = """
# nothing here
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 40]"
bytecode_length = 8
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tret
"""

[output.vm]
bytes_read = 9
instructions_executed = 2
jumps_performed = 0
max_stack_height = 1
stack_allocations = 1
