script = """
true and true
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[35, 4, 109, 97, 105, 110, 24, 24, 15, 37]"
bytecode_length = 10
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_true
7 \tpush_true
8 \tand
9 \tret
"""

[output.vm]
bytes_read = 11
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
