script = """
2 <= 3 and 2 > 1
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 2, 29, 0, 0, 0, 3, 6, 29, 0, 0, 0, 2, 29, 0, 0, 0, 1, 6, 19, 15, 40]"
bytecode_length = 32
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 2)
12 \tpush_integer (value: 3)
17 \tint_lte
18 \tpush_integer (value: 2)
23 \tpush_integer (value: 1)
28 \tint_lte
29 \tnot
30 \tand
31 \tret
"""

[output.vm]
bytes_read = 33
instructions_executed = 10
jumps_performed = 0
max_stack_height = 3
stack_allocations = 9
