script = """
false and false
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 25, 25, 15, 38]"
bytecode_length = 10
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_false
7 \tpush_false
8 \tand
9 \tret
"""

[output.vm]
bytes_read = 11
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
