script = """
true and false
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 26, 27, 15, 40]"
bytecode_length = 11
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_true
8 \tpush_false
9 \tand
10 \tret
"""

[output.vm]
bytes_read = 12
instructions_executed = 5
jumps_performed = 0
max_stack_height = 2
stack_allocations = 4
