script = """
true and (false or true)
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 26, 27, 26, 16, 15, 40]"
bytecode_length = 13
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_true
8 \tpush_false
9 \tpush_true
10 \tor
11 \tand
12 \tret
"""

[output.vm]
bytes_read = 14
instructions_executed = 7
jumps_performed = 0
max_stack_height = 3
stack_allocations = 6
