script = """
false or (true and (false or true))
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 25, 24, 25, 24, 16, 15, 16, 38]"
bytecode_length = 14
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_false
7 \tpush_true
8 \tpush_false
9 \tpush_true
10 \tor
11 \tand
12 \tor
13 \tret
"""

[output.vm]
bytes_read = 15
instructions_executed = 9
jumps_performed = 0
max_stack_height = 4
stack_allocations = 8
