script = """
false
"""

[output]
result = "false"
type = "boolean"

[output.compiler]
bytecode = "[35, 4, 109, 97, 105, 110, 25, 37]"
bytecode_length = 8
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_false
7 \tret
"""

[output.vm]
bytes_read = 9
instructions_executed = 3
jumps_performed = 0
max_stack_height = 1
stack_allocations = 2
