script = """
true
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 26, 40]"
bytecode_length = 9
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_true
8 \tret
"""

[output.vm]
bytes_read = 10
instructions_executed = 3
jumps_performed = 0
max_stack_height = 1
stack_allocations = 2
