script = """
true and (false or true)
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 26, 27, 26, 16, 15, 40]"
bytecode_length = 12
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_true
7 \tpush_false
8 \tpush_true
9 \tor
10 \tand
11 \tret
"""

[output.vm]
bytes_read = 13
instructions_executed = 7
jumps_performed = 0
max_stack_height = 3
stack_allocations = 6
