script = """
false or (true and (false or true))
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 27, 26, 27, 26, 16, 15, 16, 40]"
bytecode_length = 15
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_false
8 \tpush_true
9 \tpush_false
10 \tpush_true
11 \tor
12 \tand
13 \tor
14 \tret
"""

[output.vm]
bytes_read = 16
instructions_executed = 9
jumps_performed = 0
max_stack_height = 4
stack_allocations = 8
