script = """
2 + 2 is
    4
        "yes"
    _
        "no"
"""

[output]
result = "yes"
type = "string"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 27, 0, 0, 0, 2, 27, 0, 0, 0, 2, 0, 21, 0, 20, 0, 27, 0, 0, 0, 4, 17, 44, 0, 8, 28, 3, 121, 101, 115, 42, 0, 4, 28, 2, 110, 111, 38]"
bytecode_length = 43
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_integer (value: 2)
11 \tpush_integer (value: 2)
16 \tint_add
17 \tset_value (index: 0)
19 \tget_value (index: 0)
21 \tpush_integer (value: 4)
26 \teq
27 \tjump if false (offset: 8, to byte 38)
30 \tpush_string (value: 'yes')
35 \tjump (offset: 4, to byte 42)
38 \tpush_string (value: 'no')
42 \tret
"""

[output.vm]
bytes_read = 40
instructions_executed = 12
jumps_performed = 1
max_stack_height = 3
stack_allocations = 8
