script = """
2 is
    1
        "no"
    other if 2 + 2
        "value captured is {other}"
"""

[output]
error = """
    other if 2 + 2
               \u001B[33m^\u001B[0m
Line 4.16: Expected bool but got int."""
