script = """
2.5 is
    other if other >=. 2.0 and other <. 3.0
        "captured {other}"
"""

[output]
result = "captured 2.5"
type = "string"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 26, 64, 32, 0, 0, 21, 0, 26, 64, 32, 0, 0, 21, 0, 20, 0, 26, 64, 0, 0, 0, 12, 19, 20, 0, 26, 64, 64, 0, 0, 12, 15, 44, 0, 14, 28, 9, 99, 97, 112, 116, 117, 114, 101, 100, 32, 20, 0, 14, 38]"
bytecode_length = 56
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_float (value: 2.5)
11 \tset_value (index: 0)
13 \tpush_float (value: 2.5)
18 \tset_value (index: 0)
20 \tget_value (index: 0)
22 \tpush_float (value: 2)
27 \tfloat_lt
28 \tnot
29 \tget_value (index: 0)
31 \tpush_float (value: 3)
36 \tfloat_lt
37 \tand
38 \tjump if false (offset: 14, to byte 55)
41 \tpush_string (value: 'captured ')
52 \tget_value (index: 0)
54 \tstr_concat
55 \tret
"""

[output.vm]
bytes_read = 57
instructions_executed = 18
jumps_performed = 0
max_stack_height = 5
stack_allocations = 14
