script = """
3 is
    1 + 1 + 1
        "yes"
    _
        "no"
"""

[output]
result = "yes"
type = "string"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 3, 21, 0, 20, 0, 29, 0, 0, 0, 1, 29, 0, 0, 0, 1, 0, 29, 0, 0, 0, 1, 0, 17, 46, 0, 8, 30, 3, 121, 101, 115, 44, 0, 4, 30, 2, 110, 111, 40]"
bytecode_length = 50
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 3)
12 \tset_value (index: 0)
14 \tget_value (index: 0)
16 \tpush_integer (value: 1)
21 \tpush_integer (value: 1)
26 \tint_add
27 \tpush_integer (value: 1)
32 \tint_add
33 \teq
34 \tjump if false (offset: 8, to byte 45)
37 \tpush_string (value: 'yes')
42 \tjump (offset: 4, to byte 49)
45 \tpush_string (value: 'no')
49 \tret
"""

[output.vm]
bytes_read = 47
instructions_executed = 14
jumps_performed = 1
max_stack_height = 4
stack_allocations = 10
