script = """
:hello is
    :yo
        "dawg"
    :hello
        "world"
    :hi
        "john"
"""

[output]
result = "world"
type = "string"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 33, 6, 58, 104, 101, 108, 108, 111, 21, 0, 20, 0, 33, 3, 58, 121, 111, 17, 46, 0, 9, 30, 4, 100, 97, 119, 103, 44, 0, 41, 20, 0, 33, 6, 58, 104, 101, 108, 108, 111, 17, 46, 0, 10, 30, 5, 119, 111, 114, 108, 100, 44, 0, 17, 20, 0, 33, 3, 58, 104, 105, 17, 46, 0, 6, 30, 4, 106, 111, 104, 110, 40]"
bytecode_length = 79
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_simple_tag (value: ':hello')
15 \tset_value (index: 0)
17 \tget_value (index: 0)
19 \tpush_simple_tag (value: ':yo')
24 \teq
25 \tjump if false (offset: 9, to byte 37)
28 \tpush_string (value: 'dawg')
34 \tjump (offset: 41, to byte 78)
37 \tget_value (index: 0)
39 \tpush_simple_tag (value: ':hello')
47 \teq
48 \tjump if false (offset: 10, to byte 61)
51 \tpush_string (value: 'world')
58 \tjump (offset: 17, to byte 78)
61 \tget_value (index: 0)
63 \tpush_simple_tag (value: ':hi')
68 \teq
69 \tjump if false (offset: 6, to byte 78)
72 \tpush_string (value: 'john')
78 \tret
"""

[output.vm]
bytes_read = 54
instructions_executed = 14
jumps_performed = 2
max_stack_height = 3
stack_allocations = 9
