script = """
:hello is
    :yo
        "dawg"
    :hello
        "world"
    :hi
        "john"
"""

[output]
result = "world"
type = "string"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 33, 6, 58, 104, 101, 108, 108, 111, 21, 0, 20, 0, 33, 3, 58, 121, 111, 17, 46, 0, 9, 30, 4, 100, 97, 119, 103, 44, 0, 41, 20, 0, 33, 6, 58, 104, 101, 108, 108, 111, 17, 46, 0, 10, 30, 5, 119, 111, 114, 108, 100, 44, 0, 17, 20, 0, 33, 3, 58, 104, 105, 17, 46, 0, 6, 30, 4, 106, 111, 104, 110, 40]"
bytecode_length = 78
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_simple_tag (value: ':hello')
14 \tset_value (index: 0)
16 \tget_value (index: 0)
18 \tpush_simple_tag (value: ':yo')
23 \teq
24 \tjump if false (offset: 9, to byte 36)
27 \tpush_string (value: 'dawg')
33 \tjump (offset: 41, to byte 77)
36 \tget_value (index: 0)
38 \tpush_simple_tag (value: ':hello')
46 \teq
47 \tjump if false (offset: 10, to byte 60)
50 \tpush_string (value: 'world')
57 \tjump (offset: 17, to byte 77)
60 \tget_value (index: 0)
62 \tpush_simple_tag (value: ':hi')
67 \teq
68 \tjump if false (offset: 6, to byte 77)
71 \tpush_string (value: 'john')
77 \tret
"""

[output.vm]
bytes_read = 53
instructions_executed = 14
jumps_performed = 2
max_stack_height = 3
stack_allocations = 9
