script = '''
square = \v
    v * v

add = \v1 v2
    v1 + v2

add_one = \v
    v | add 1

5 | square | add 3 | add_one
'''

[output]
result = "29"
type = "integer"

[output.compiler]
bytecode = "[0, 37, 6, 115, 113, 117, 97, 114, 101, 1, 0, 95, 37, 3, 97, 100, 100, 2, 0, 109, 37, 7, 97, 100, 100, 95, 111, 110, 101, 1, 0, 120, 38, 4, 109, 97, 105, 110, 39, 0, 1, 21, 0, 39, 1, 2, 21, 1, 39, 2, 1, 21, 2, 29, 0, 0, 0, 5, 41, 1, 0, 0, 6, 115, 113, 117, 97, 114, 101, 29, 0, 0, 0, 3, 41, 2, 0, 1, 3, 97, 100, 100, 41, 1, 0, 2, 7, 97, 100, 100, 95, 111, 110, 101, 40, 38, 6, 115, 113, 117, 97, 114, 101, 20, 0, 20, 0, 3, 40, 38, 3, 97, 100, 100, 20, 0, 20, 1, 0, 40, 38, 7, 97, 100, 100, 95, 111, 110, 101, 20, 0, 29, 0, 0, 0, 1, 41, 2, 1, 1, 3, 97, 100, 100, 40]"
bytecode_length = 145
disassembled = """
0 \tComponent Count: 0
1 \tfunction signature (name: square) (local count: 1) (function position: 95)
12 \tfunction signature (name: add) (local count: 2) (function position: 109)
20 \tfunction signature (name: add_one) (local count: 1) (function position: 120)

32 \t=== function chunk: main ===
38 \tfunction (function index: 0) (params: 1)
41 \tset_value (index: 0)
43 \tfunction (function index: 1) (params: 2)
46 \tset_value (index: 1)
48 \tfunction (function index: 2) (params: 1)
51 \tset_value (index: 2)
53 \tpush_integer (value: 5)
58 \tcall square (is_global: 0) (arg count: 1, function index: 0)
69 \tpush_integer (value: 3)
74 \tcall add (is_global: 0) (arg count: 2, function index: 1)
82 \tcall add_one (is_global: 0) (arg count: 1, function index: 2)
94 \tret

95 \t=== function chunk: square ===
103 \tget_value (index: 0)
105 \tget_value (index: 0)
107 \tint_mult
108 \tret

109 \t=== function chunk: add ===
114 \tget_value (index: 0)
116 \tget_value (index: 1)
118 \tint_add
119 \tret

120 \t=== function chunk: add_one ===
129 \tget_value (index: 0)
131 \tpush_integer (value: 1)
136 \tcall add (is_global: 1) (arg count: 2, function index: 1)
144 \tret
"""

[output.vm]
bytes_read = 157
instructions_executed = 33
jumps_performed = 0
max_stack_height = 8
stack_allocations = 21
