script = """
""
"""

[output]
result = ""
type = "string"

[output.compiler]
bytecode = "[36, 4, 109, 97, 105, 110, 28, 0, 38]"
bytecode_length = 9
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_string (value: '')
8 \tret
"""

[output.vm]
bytes_read = 10
instructions_executed = 3
jumps_performed = 0
max_stack_height = 1
stack_allocations = 2
