script = """
"{2} * {2 + 1} == {2 * (2 + 1)}"
"""

[output]
result = "2 * 3 == 6"
type = "string"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 30, 0, 29, 0, 0, 0, 2, 14, 30, 3, 32, 42, 32, 14, 29, 0, 0, 0, 2, 29, 0, 0, 0, 1, 0, 14, 30, 4, 32, 61, 61, 32, 14, 29, 0, 0, 0, 2, 29, 0, 0, 0, 2, 29, 0, 0, 0, 1, 0, 3, 14, 40]"
bytecode_length = 59
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_string (value: '')
9 \tpush_integer (value: 2)
14 \tstr_concat
15 \tpush_string (value: ' * ')
20 \tstr_concat
21 \tpush_integer (value: 2)
26 \tpush_integer (value: 1)
31 \tint_add
32 \tstr_concat
33 \tpush_string (value: ' == ')
39 \tstr_concat
40 \tpush_integer (value: 2)
45 \tpush_integer (value: 2)
50 \tpush_integer (value: 1)
55 \tint_add
56 \tint_mult
57 \tstr_concat
58 \tret
"""

[output.vm]
bytes_read = 60
instructions_executed = 19
jumps_performed = 0
max_stack_height = 4
stack_allocations = 18
