script = """
"result is {2 * 2 == 4}!"
"""

[output]
result = "result is true!"
type = "string"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 30, 10, 114, 101, 115, 117, 108, 116, 32, 105, 115, 32, 29, 0, 0, 0, 2, 29, 0, 0, 0, 2, 3, 29, 0, 0, 0, 4, 17, 14, 30, 1, 33, 14, 40]"
bytecode_length = 42
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_string (value: 'result is ')
19 \tpush_integer (value: 2)
24 \tpush_integer (value: 2)
29 \tint_mult
30 \tpush_integer (value: 4)
35 \teq
36 \tstr_concat
37 \tpush_string (value: '!')
40 \tstr_concat
41 \tret
"""

[output.vm]
bytes_read = 43
instructions_executed = 11
jumps_performed = 0
max_stack_height = 3
stack_allocations = 10
