script = """
"float value is {0.1 +. 0.2}"
"""

[output]
result = "float value is 0.3"
type = "string"

[output.compiler]
bytecode = "[38, 4, 109, 97, 105, 110, 30, 15, 102, 108, 111, 97, 116, 32, 118, 97, 108, 117, 101, 32, 105, 115, 32, 28, 61, 204, 204, 205, 28, 62, 76, 204, 205, 7, 14, 40]"
bytecode_length = 36
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_string (value: 'float value is ')
23 \tpush_float (value: 0.1)
28 \tpush_float (value: 0.2)
33 \tfloat_add
34 \tstr_concat
35 \tret
"""

[output.vm]
bytes_read = 37
instructions_executed = 7
jumps_performed = 0
max_stack_height = 3
stack_allocations = 6
