script = """
""
"""

[output]
result = ""
type = "string"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 30, 0, 40]"
bytecode_length = 10
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_string (value: '')
9 \tret
"""

[output.vm]
bytes_read = 11
instructions_executed = 3
jumps_performed = 0
max_stack_height = 1
stack_allocations = 2
