script = '''
greeting = \name
    "Hello {name}!"

"John" | greeting
'''

[output]
result = "Hello John!"
type = "string"

[output.compiler]
bytecode = "[35, 8, 103, 114, 101, 101, 116, 105, 110, 103, 1, 0, 44, 36, 4, 109, 97, 105, 110, 37, 0, 1, 21, 0, 28, 4, 74, 111, 104, 110, 39, 1, 0, 0, 8, 103, 114, 101, 101, 116, 105, 110, 103, 38, 36, 8, 103, 114, 101, 101, 116, 105, 110, 103, 28, 6, 72, 101, 108, 108, 111, 32, 20, 0, 14, 28, 1, 33, 14, 38]"
bytecode_length = 70
disassembled = """
0 \tfunction signature (name: greeting) (local count: 1) (function position: 44)

13 \t=== function chunk: main ===
19 \tfunction (function index: 0) (params: 1)
22 \tset_value (index: 0)
24 \tpush_string (value: 'John')
30 \tcall greeting (is_global: 0) (arg count: 1, function index: 0)
43 \tret

44 \t=== function chunk: greeting ===
54 \tpush_string (value: 'Hello ')
62 \tget_value (index: 0)
64 \tstr_concat
65 \tpush_string (value: '!')
68 \tstr_concat
69 \tret
"""

[output.vm]
bytes_read = 71
instructions_executed = 13
jumps_performed = 0
max_stack_height = 4
stack_allocations = 9
