script = """
"Hello {(40 + 2) / 2}"
"""

[output]
result = "Hello 21"
type = "string"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 30, 6, 72, 101, 108, 108, 111, 32, 29, 0, 0, 0, 40, 29, 0, 0, 0, 2, 0, 29, 0, 0, 0, 2, 2, 14, 40]"
bytecode_length = 34
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_string (value: 'Hello ')
15 \tpush_integer (value: 40)
20 \tpush_integer (value: 2)
25 \tint_add
26 \tpush_integer (value: 2)
31 \tint_div
32 \tstr_concat
33 \tret
"""

[output.vm]
bytes_read = 35
instructions_executed = 9
jumps_performed = 0
max_stack_height = 3
stack_allocations = 8
