script = """
"Hello {40 + 2}"
"""

[output]
result = "Hello 42"
type = "string"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 30, 6, 72, 101, 108, 108, 111, 32, 29, 0, 0, 0, 40, 29, 0, 0, 0, 2, 0, 14, 40]"
bytecode_length = 28
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_string (value: 'Hello ')
15 \tpush_integer (value: 40)
20 \tpush_integer (value: 2)
25 \tint_add
26 \tstr_concat
27 \tret
"""

[output.vm]
bytes_read = 29
instructions_executed = 7
jumps_performed = 0
max_stack_height = 3
stack_allocations = 6
