script = """
"{2} * {2 + 1} == {2 * (2 + 1)}"
"""

[output]
result = "2 * 3 == 6"
type = "string"

[output.compiler]
bytecode = "[35, 4, 109, 97, 105, 110, 28, 0, 27, 0, 0, 0, 2, 14, 28, 3, 32, 42, 32, 14, 27, 0, 0, 0, 2, 27, 0, 0, 0, 1, 0, 14, 28, 4, 32, 61, 61, 32, 14, 27, 0, 0, 0, 2, 27, 0, 0, 0, 2, 27, 0, 0, 0, 1, 0, 3, 14, 37]"
bytecode_length = 58
disassembled = """

0 \t=== function chunk: main ===
6 \tpush_string (value: '')
8 \tpush_integer (value: 2)
13 \tstr_concat
14 \tpush_string (value: ' * ')
19 \tstr_concat
20 \tpush_integer (value: 2)
25 \tpush_integer (value: 1)
30 \tint_add
31 \tstr_concat
32 \tpush_string (value: ' == ')
38 \tstr_concat
39 \tpush_integer (value: 2)
44 \tpush_integer (value: 2)
49 \tpush_integer (value: 1)
54 \tint_add
55 \tint_mult
56 \tstr_concat
57 \tret
"""

[output.vm]
bytes_read = 59
instructions_executed = 19
jumps_performed = 0
max_stack_height = 4
stack_allocations = 18
