script = '''
add_one = \v
    x = 1
    y = x
    v + y

5 | add_one
'''

[output]
result = "6"
type = "integer"

[output.compiler]
bytecode = "[35, 7, 97, 100, 100, 95, 111, 110, 101, 1, 0, 41, 36, 4, 109, 97, 105, 110, 37, 0, 1, 21, 0, 27, 0, 0, 0, 5, 39, 1, 0, 0, 7, 97, 100, 100, 95, 111, 110, 101, 38, 36, 7, 97, 100, 100, 95, 111, 110, 101, 27, 0, 0, 0, 1, 21, 1, 20, 1, 21, 2, 20, 0, 20, 2, 0, 38]"
bytecode_length = 67
disassembled = """
0 \tfunction signature (name: add_one) (local count: 1) (function position: 41)

12 \t=== function chunk: main ===
18 \tfunction (function index: 0) (params: 1)
21 \tset_value (index: 0)
23 \tpush_integer (value: 5)
28 \tcall add_one (is_global: 0) (arg count: 1, function index: 0)
40 \tret

41 \t=== function chunk: add_one ===
50 \tpush_integer (value: 1)
55 \tset_value (index: 1)
57 \tget_value (index: 1)
59 \tset_value (index: 2)
61 \tget_value (index: 0)
63 \tget_value (index: 2)
65 \tint_add
66 \tret
"""

[output.vm]
bytes_read = 68
instructions_executed = 15
jumps_performed = 0
max_stack_height = 6
stack_allocations = 9
