script = '''
match = \tag
	tag is
		x
			"captured value {x}"
(:yellow 4) | match
'''

[output]
result = "captured value :yellow(4)"
type = "string"

[output.compiler]
bytecode = "[37, 5, 109, 97, 116, 99, 104, 1, 0, 46, 38, 4, 109, 97, 105, 110, 39, 0, 1, 21, 0, 29, 0, 0, 0, 4, 34, 7, 58, 121, 101, 108, 108, 111, 119, 41, 1, 0, 0, 5, 109, 97, 116, 99, 104, 40, 38, 5, 109, 97, 116, 99, 104, 30, 15, 99, 97, 112, 116, 117, 114, 101, 100, 32, 118, 97, 108, 117, 101, 32, 20, 0, 14, 40]"
bytecode_length = 74
disassembled = """
0 \tfunction signature (name: match) (local count: 1) (function position: 46)

10 \t=== function chunk: main ===
16 \tfunction (function index: 0) (params: 1)
19 \tset_value (index: 0)
21 \tpush_integer (value: 4)
26 \tpush_tag (value: ':yellow')
35 \tcall match (is_global: 0) (arg count: 1, function index: 0)
45 \tret

46 \t=== function chunk: match ===
53 \tpush_string (value: 'captured value ')
70 \tget_value (index: 0)
72 \tstr_concat
73 \tret
"""

[output.vm]
bytes_read = 75
instructions_executed = 12
jumps_performed = 0
max_stack_height = 4
stack_allocations = 8
