script = '''
match = \tag
	tag is
		:container x
			"container with value {x}"
		_
			"no match"
(:container 4) | match
'''

[output]
result = "container with value 4"
type = "string"

[output.compiler]
bytecode = "[37, 5, 109, 97, 116, 99, 104, 1, 0, 49, 38, 4, 109, 97, 105, 110, 39, 0, 1, 21, 0, 29, 0, 0, 0, 4, 34, 10, 58, 99, 111, 110, 116, 97, 105, 110, 101, 114, 41, 1, 0, 0, 5, 109, 97, 116, 99, 104, 40, 38, 5, 109, 97, 116, 99, 104, 35, 30, 10, 58, 99, 111, 110, 116, 97, 105, 110, 101, 114, 17, 46, 0, 30, 36, 30, 21, 99, 111, 110, 116, 97, 105, 110, 101, 114, 32, 119, 105, 116, 104, 32, 118, 97, 108, 117, 101, 32, 20, 1, 14, 44, 0, 10, 30, 8, 110, 111, 32, 109, 97, 116, 99, 104, 40]"
bytecode_length = 114
disassembled = """
0 \tfunction signature (name: match) (local count: 1) (function position: 49)

10 \t=== function chunk: main ===
16 \tfunction (function index: 0) (params: 1)
19 \tset_value (index: 0)
21 \tpush_integer (value: 4)
26 \tpush_tag (value: ':container')
38 \tcall match (is_global: 0) (arg count: 1, function index: 0)
48 \tret

49 \t=== function chunk: match ===
56 \tget_tag_name
57 \tpush_string (value: ':container')
69 \teq
70 \tjump if false (offset: 30, to byte 103)
73 \tget_tag_payload
74 \tpush_string (value: 'container with value ')
97 \tget_value (index: 1)
99 \tstr_concat
100 \tjump (offset: 10, to byte 113)
103 \tpush_string (value: 'no match')
113 \tret
"""

[output.vm]
bytes_read = 105
instructions_executed = 18
jumps_performed = 1
max_stack_height = 5
stack_allocations = 12
